from lean4py.logic import (
    Prop,
    Prop_var,
    implies,
    and_,
    or_,
    not_,
    iff,
    Theorem,
    ProofStep,
    assume,
    have,
    exact,
    apply,
    rfl,
    simp,
    prove,
)

from lean4py.sets import (
    Set,
    Set_from,
    in_,
    subset,
    union,
    intersection,
    complement,
    difference,
    cartesian,
    power_set,
    empty_set,
)

from lean4py.algebra import (
    Magma,
    Semigroup,
    Monoid,
    Group,
    AbelianGroup,
    Ring,
    Field,
)

from lean4py.nat import (
    Nat,
    nat,
    zero,
    succ,
    pred,
    is_zero,
    nat_add,
    nat_mul,
    nat_sub,
    nat_le,
    nat_lt,
    nat_eq,
)

from lean4py.tactics import (
    Tactic,
    tactic_rfl,
    tactic_exact,
    tactic_apply,
    tactic_simp,
    tactic_assume,
    tactic_have,
    TacticProof,
    TacticState,
    intros,
    intros_tactic,
    by_contra,
    by_contra_tactic,
    cases,
    cases_tactic,
    induction,
    induction_tactic,
    rewrite,
    rewrite_tactic,
    split,
    split_tactic,
    left,
    left_tactic,
    right,
    right_tactic,
    use,
    use_tactic,
    show,
    show_tactic,
    by,
    by_tactic,
    sorry,
    sorry_tactic,
    calc,
    calc_tactic,
    intro,
    intro_tactic,
    apply_tactic,
)

from lean4py.prover import (
    Prover,
    truth_table_prove,
    tableau_prove,
    is_valid,
    is_satisfiable,
    find_counterexample,
)

from lean4py.number_theory import (
    Integer,
    int_,
    zero,
    one,
    gcd,
    lcm,
    bezout_identity,
    is_prime,
    prime_factors,
    phi,
    mod_exp,
    mod_inverse,
    divides,
    coprime,
    chinese_remainder,
    fundamental_theorem_of_arithmetic,
    IntegerInduction,
)

from lean4py.linear_algebra import (
    Vector,
    vector,
    zero_vector,
    dot_product,
    cross_product,
    angle_between,
    projection,
    Matrix,
    matrix,
    identity_matrix,
    zero_matrix,
    matrix_mul,
    matrix_vector_mul,
    det,
    matrix_minor,
    matrix_inverse,
    trace,
    rank,
    nullity,
    eigenvalues,
    eigenvectors,
    is_linearly_independent,
    span,
    is_orthogonal,
    is_orthonormal,
    LinearMap,
    linear_map,
)

from lean4py.real_analysis import (
    Real,
    real,
    limit,
    limit_left,
    limit_right,
    derivative,
    partial_derivative,
    integral,
    riemann_sum,
    series_sum,
    infinite_series_sum,
    converges,
    is_continuous,
    is_differentiable,
    taylor_series,
    lhopital_limit,
    sequence_limit,
    is_monotonic,
    is_bounded,
    Sequence,
    mclaurin_series,
    Function,
)

from lean4py.probability import (
    ProbabilitySpace,
    Event,
    RandomVariable,
    ExpectedValue,
    Variance,
    StandardDeviation,
    Covariance,
    Correlation,
    NormalDistribution,
    BinomialDistribution,
    PoissonDistribution,
    UniformDistribution,
    bayes_theorem,
    law_of_total_probability,
    hypothesis_test,
    confidence_interval,
)

from lean4py.graph_theory import (
    Graph,
    Vertex,
    Edge,
    adjacency_list,
    adjacency_matrix,
    bfs,
    dfs,
    shortest_path,
    dijkstra,
    bellman_ford,
    is_connected,
    is_bipartite,
    connected_components,
    has_cycle,
    topological_sort,
    eulerian_path,
    spanning_tree,
    minimum_spanning_tree,
    is_complete,
)

__version__ = "0.4.0"
__all__ = [
    "Prop", "Prop_var", "implies", "and_", "or_", "not_", "iff",
    "Theorem", "ProofStep", "assume", "have", "exact", "apply", "rfl", "simp", "prove",
    "Set", "Set_from", "in_", "subset", "union", "intersection", "complement",
    "difference", "cartesian", "power_set", "empty_set",
    "Magma", "Semigroup", "Monoid", "Group", "AbelianGroup", "Ring", "Field",
    "Nat", "nat", "zero", "succ", "pred", "is_zero",
    "nat_add", "nat_mul", "nat_sub", "nat_le", "nat_lt", "nat_eq",
    "Tactic", "tactic_rfl", "tactic_exact", "tactic_apply", "tactic_simp",
    "tactic_assume", "tactic_have", "TacticProof", "TacticState",
    "intros", "intros_tactic",
    "by_contra", "by_contra_tactic",
    "cases", "cases_tactic",
    "induction", "induction_tactic",
    "rewrite", "rewrite_tactic",
    "split", "split_tactic",
    "left", "left_tactic",
    "right", "right_tactic",
    "use", "use_tactic",
    "show", "show_tactic",
    "by", "by_tactic",
    "sorry", "sorry_tactic",
    "calc", "calc_tactic",
    "intro", "intro_tactic",
    "apply_tactic",
    "Prover", "truth_table_prove", "tableau_prove",
    "is_valid", "is_satisfiable", "find_counterexample",
    "Integer", "int_", "one",
    "gcd", "lcm", "bezout_identity",
    "is_prime", "prime_factors", "phi",
    "mod_exp", "mod_inverse", "divides", "coprime",
    "chinese_remainder", "fundamental_theorem_of_arithmetic",
    "IntegerInduction",
    "Vector", "zero_vector", "dot_product", "cross_product",
    "angle_between", "projection",
    "Matrix", "matrix", "identity_matrix", "zero_matrix",
    "matrix_mul", "matrix_vector_mul",
    "det", "matrix_minor", "matrix_inverse", "trace",
    "rank", "nullity", "eigenvalues", "eigenvectors",
    "is_linearly_independent", "span",
    "is_orthogonal", "is_orthonormal",
    "LinearMap", "linear_map",
    "Real", "real", "limit", "derivative", "integral",
    "series_sum", "converges", "is_continuous", "is_differentiable",
    "taylor_series", "lhopital_limit", "Sequence", "Function",
    "ProbabilitySpace", "Event", "RandomVariable",
    "ExpectedValue", "Variance", "StandardDeviation",
    "NormalDistribution", "BinomialDistribution", "PoissonDistribution",
    "bayes_theorem", "hypothesis_test", "confidence_interval",
    "Graph", "Vertex", "Edge",
    "bfs", "dfs", "shortest_path", "dijkstra",
    "is_connected", "is_bipartite", "has_cycle",
    "topological_sort", "spanning_tree", "minimum_spanning_tree",
]