from lean4py.logic import (
    Prop,
    Prop_var,
    implies,
    and_,
    or_,
    not_,
    iff,
    Theorem,
    ProofStep,
    assume,
    have,
    exact,
    apply,
    rfl,
    simp,
    prove,
)

from lean4py.sets import (
    Set,
    Set_from,
    in_,
    subset,
    union,
    intersection,
    complement,
    difference,
    symmetric_difference,
    is_disjoint,
    is_overlapping,
    cartesian,
    power_set,
    empty_set,
)

from lean4py.algebra import (
    Magma,
    Semigroup,
    Monoid,
    Group,
    AbelianGroup,
    Ring,
    Field,
)

from lean4py.nat import (
    Nat,
    nat,
    zero,
    succ,
    pred,
    is_zero,
    nat_add,
    nat_mul,
    nat_sub,
    nat_le,
    nat_lt,
    nat_eq,
    factorial,
    fibonacci,
    nat_gcd,
    nat_is_prime,
    nat_even,
    nat_odd,
)

from lean4py.tactics import (
    Tactic,
    tactic_rfl,
    tactic_exact,
    tactic_apply,
    tactic_simp,
    tactic_assume,
    tactic_have,
    TacticProof,
    TacticState,
    intros,
    intros_tactic,
    by_contra,
    by_contra_tactic,
    cases,
    cases_tactic,
    induction,
    induction_tactic,
    rewrite,
    rewrite_tactic,
    split,
    split_tactic,
    left,
    left_tactic,
    right,
    right_tactic,
    use,
    use_tactic,
    show,
    show_tactic,
    by,
    by_tactic,
    sorry,
    sorry_tactic,
    calc,
    calc_tactic,
    intro,
    intro_tactic,
    apply_tactic,
)

from lean4py.prover import (
    Prover,
    truth_table_prove,
    tableau_prove,
    is_valid,
    is_satisfiable,
    find_counterexample,
)

from lean4py.number_theory import (
    Integer,
    int_,
    zero,
    one,
    gcd,
    lcm,
    bezout_identity,
    is_prime,
    prime_factors,
    phi,
    mod_exp,
    mod_inverse,
    divides,
    coprime,
    chinese_remainder,
    fundamental_theorem_of_arithmetic,
    IntegerInduction,
)

from lean4py.linear_algebra import (
    Vector,
    vector,
    zero_vector,
    dot_product,
    cross_product,
    angle_between,
    projection,
    Matrix,
    matrix,
    identity_matrix,
    zero_matrix,
    matrix_mul,
    matrix_vector_mul,
    det,
    matrix_minor,
    matrix_inverse,
    trace,
    rank,
    nullity,
    eigenvalues,
    eigenvectors,
    is_linearly_independent,
    span,
    is_orthogonal,
    is_orthonormal,
    LinearMap,
    linear_map,
)

from lean4py.real_analysis import (
    Real,
    real,
    limit,
    limit_left,
    limit_right,
    derivative,
    partial_derivative,
    integral,
    riemann_sum,
    series_sum,
    infinite_series_sum,
    converges,
    is_continuous,
    is_differentiable,
    taylor_series,
    lhopital_limit,
    sequence_limit,
    is_monotonic,
    is_bounded,
    Sequence,
    mclaurin_series,
    Function,
    ratio_test,
    root_test,
    adaptive_simpson,
    euler_method,
    runge_kutta_4,
)

from lean4py.probability import (
    ProbabilitySpace,
    Event,
    RandomVariable,
    ExpectedValue,
    Variance,
    StandardDeviation,
    Covariance,
    Correlation,
    NormalDistribution,
    BinomialDistribution,
    PoissonDistribution,
    UniformDistribution,
    ExponentialDistribution,
    bayes_theorem,
    law_of_total_probability,
    hypothesis_test,
    confidence_interval,
)

from lean4py.graph_theory import (
    Graph,
    Vertex,
    Edge,
    adjacency_list,
    adjacency_matrix,
    bfs,
    dfs,
    shortest_path,
    dijkstra,
    bellman_ford,
    is_connected,
    is_bipartite,
    connected_components,
    has_cycle,
    topological_sort,
    eulerian_path,
    spanning_tree,
    minimum_spanning_tree,
    is_complete,
    graph_clique,
    is_eulerian,
    graph_coloring,
    complement_graph,
    has_hamiltonian_path,
)

from lean4py.statistics import (
    mean, median, mode,
    variance, std_dev,
    covariance, correlation,
    linear_regression,
    skewness, kurtosis,
    t_test_one_sample,
    confidence_interval_mean,
    anova_one_way,
    chi_square_test,
    mann_whitney_u,
    kruskal_wallis,
    linear_regression_diagnostics,
    mann_kendall,
    wilcoxon_signed_rank,
    wilcoxon_rank_sum,
)

from lean4py.symbolic import (
    symbolic_derivative,
    symbolic_integral,
    symbolic_simplify,
)

from lean4py.pde import (
    solve_heat_equation,
    solve_wave_equation,
    solve_laplace_equation,
    solve_poisson_equation,
)

from lean4py.time_series import (
    moving_average,
    autocovariance,
    acf,
    partial_acf,
)

from lean4py.ml_basics import (
    linear_regression_ml,
    logistic_regression,
    svm_linear,
    decision_tree,
    predict_tree,
    kmeans,
    random_forest,
    predict_random_forest,
)

from lean4py.information_theory import (
    entropy,
    mutual_information,
    kl_divergence,
)

from lean4py.neural_network import (
    DenseLayer,
    NeuralNetwork,
    sigmoid,
    relu,
    tanh,
    mse_loss,
    train_neural_network,
)

from lean4py.bayesian import (
    GaussianPrior,
    BetaPrior,
    posterior_update_normal,
    posterior_update_beta_binomial,
    metropolis_hastings,
    bayesian_linear_regression,
    compute_bayes_factor,
)

from lean4py.signal_processing import (
    dft,
    idft,
    fft,
    ifft,
    spectrogram,
    compute_frequency_spectrum,
)

from lean4py.linear_algebra import (
    compute_mean_vector,
    compute_covariance_matrix,
    pca,
)

from lean4py.reinforcement_learning import (
    QLearning,
    SARSA,
    epsilon_greedy,
    run_episode,
)

from lean4py.gaussian_process import (
    GaussianProcessRegressor,
    rbf_kernel,
    predict_gp,
)

from lean4py.hmm import (
    HMM,
)

from lean4py.kalman_filter import (
    KalmanFilter,
    kalman_smooth,
)

from lean4py.sparse_coding import (
    OMP,
    sparse_coding,
    compute_dictionary,
)

from lean4py.manifold_learning import (
    isomap,
    LLE,
    compute_geodesic_distances,
)

from lean4py.optimization import (
    gradient_descent,
    linear_programming,
    newton_method,
    conjugate_gradient,
    lagrange_multiplier,
    penalty_method,
    augmented_lagrange,
    bfgs,
    lbfgs,
    newton_raphson,
    levenberg_marquardt,
)

from lean4py.homological_algebra import (
    ChainComplex,
    CochainComplex,
    LongExactSequence,
    Ext,
    Tor,
)

from lean4py.sheaf import (
    TopologicalSpace,
    Presheaf,
    Sheaf,
    SheafCohomology,
    AffineScheme,
    Spec,
)

from lean4py.lie_algebra import (
    LieAlgebra,
    LieSubalgebra,
    LieAlgebraRepresentation,
    AdjointRepresentation,
    UniversalEnvelopingAlgebra,
    SerreRelations,
    RootSystem,
    sl2_lie_algebra,
    gl2_lie_algebra,
)

from lean4py.representation_theory import (
    GroupRepresentation,
    RepresentationHomomorphism,
    Character,
    IrreducibleRepresentation,
    RegularRepresentation,
    InducedRepresentation,
    FrobeniusReciprocity,
    MaschkeTheorem,
    TensorProductRepresentations,
    CharacterTable,
)

from lean4py.lie_groups import (
    LieGroup,
    ClosedSubgroup,
    LieSubgroup,
    UnitaryRepresentation,
    AdjointRepresentation,
    ExponentialMap,
    BakerCampbellHausdorff,
    LieGroupCorrespondence,
    ClassicalGroups,
    OneParameterSubgroup,
    LieGroupHomomorphism,
    CompactLieGroup,
    MaximalTorus,
    WeightLattice,
    CorootLattice,
    WeylChamber,
    WeylGroupOrbit,
    HighestWeightRep,
    WeylDimensionFormula,
    CompactGroupClassification,
    IntegrationOverGroup,
)

from lean4py.stacks import (
    Groupoid,
    PresheafOfGroupoids,
    Stack,
    DMStack,
    ArtinStack,
    ModuliSpace,
    GITQuotient,
    DescentData,
    FiberedCategory,
    CechCohomology,
    CechComplex,
    SheafCohomologyGroups,
    DerivedPushforward,
    SpectralSequenceConvergence,
    LeraySpectralSequence,
    GrothendieckHigherDirectImage,
    CartesianMorphism,
    StackModuli,
    PicardStack,
    StabilityCondition,
    GeometricInvariantTheory,
    FormalSmoothMorphisms,
    FormalUnramified,
)

from lean4py.free_probability import (
    FreeProbabilitySpace,
    FreeRandomVariable,
    FreeCentralLimitTheorem,
    MarchenkoPastur,
    FreeConvolution,
    NoncommutativeSpace,
    SpectralTriple,
    ConnesDifferential,
    SpectralFlow,
    FredholmModule,
)

from lean4py.adjunction_representation import (
    AdjointAction,
    Centralizer,
    CoadjointRepresentation,
    KirillovOrbit,
    FlagVariety,
    BorelSubgroup,
    AdjointOrbit,
    NilpotentOrbit,
    OrbitMethod,
    RootDecomposition,
    PositiveSystem,
    BorelSubalgebra,
    ParabolicSubalgebra,
    VermaModuleIndex,
    CharacterFormula,
)

from lean4py.derived_categories import (
    DerivedCategory,
    Hot,
    TriangulatedCategory,
    StableCategory,
    DerivedFunctor,
    RHom,
    Lf,
    Rf,
    TorsionProduct,
    ExtGroup,
    HomologicalComplex,
    ConnesExactTriangle,
)

from lean4py.free_operator_algebras import (
    FreeGroup,
    FreeGroupCStarAlgebra,
    ReducedFreeGroupCStar,
    FreeGroupVonNeumannAlgebra,
    II1Factor,
    FreeProductCStarAlgebra,
    AmalgamatedFreeProduct,
    ReducedFreeProduct,
    FourierTransformOnGroups,
    PlancherelTheorem,
    GroupCStarAlgebra,
    CrossedProduct,
)

from lean4py.kahler_geometry import (
    ComplexManifold,
    AlmostComplexStructure,
    HermitianMetric,
    KahlerManifold,
    KahlerMetric,
    ChernConnection,
    FirstChernClass,
    HolomorphicSection,
    ComplexProjectiveSpace,
    HermitianEinsteinMetric,
    CalabiYauManifold,
    ComplexSubmanifold,
    CohomologyRing,
    HolomorphicVectorBundle,
)

from lean4py.spectral_sequence import (
    SpectralSequence,
    AdamsSpectralSequence,
    SerreSpectralSequence,
    ExactCouple,
    Hypercohomology,
    FilteredComplex,
    CohomologySpectralSequence,
    HomologySpectralSequence,
)

from lean4py.topos import (
    Topos,
    SheafTopos,
    BooleanTopos,
    AbelianCategory,
    Monomorphism,
    Epimorphism,
    ProjectiveObject,
    InjectiveObject,
    Generator,
    Cogenerator,
    ExactFunctor,
    LeftExactFunctor,
    RightExactFunctor,
    Kernel,
    Cokernel,
    Image,
    ExactSequence,
)

from lean4py.lie_algebra_classification import (
    DynkinDiagram,
    ClassificationTheorem,
    Weight,
    HighestWeightVector,
    RootSystem,
    WeylGroup,
    VermaModule,
    KostantForm,
    SimpleLieAlgebra,
)

from lean4py.hopf_algebra import (
    Coalgebra,
    Bialgebra,
    HopfAlgebra,
    GroupAlgebra,
    QuantumGroup,
    ModuleAlgebra,
    InvariantTheory,
    RepresentationOfHopfAlgebra,
    sl2_hopf,
    sl2_quantized,
    DualHopfAlgebra,
    braided_category,
)

from lean4py.model_category import (
    ModelCategory,
    QuillenAdjunction,
    HomotopyCategory,
    HomotopyEquivalence,
    CWComplex,
    SimplicialModelCategory,
    WhiteheadTheorem,
    Cofibration,
    Fibration,
    WeakEquivalence,
    WeakFactorizationSystem,
    AnodyneExtension,
    HomotopyCoherent,
)

from lean4py.algebraic_geometry import (
    ProjectiveSpace,
    AlgebraicCurve,
    RiemannRochResult,
    Divisor,
    LineBundle,
    EllipticCurve,
    Grassmannian,
    RationalNormalCurve,
    blowing_up,
    SheafCohomologyAlgebraic,
)

from lean4py.numerical_methods import (
    NewtonRaphson,
    SecantMethod,
    BisectionMethod,
    FixedPointIteration,
    LagrangeInterpolation,
    NewtonInterpolation,
    GaussianQuadrature,
    SimpsonRule,
    RombergIntegration,
)

from lean4py.graph_algorithms import (
    GraphIsomorphism,
    Treewidth,
    PlanarGraph,
    EulerianCircuit,
    HamiltonianCycle,
    GraphColoring,
    Matching,
    VertexCover,
    NetworkFlow,
    GraphCentrality,
)

from lean4py.topos import (
    Topos,
    SheafTopos,
    BooleanTopos,
    AbelianCategory,
    Monomorphism,
    Epimorphism,
    ProjectiveObject,
    InjectiveObject,
    Generator,
    Cogenerator,
    ExactFunctor,
    LeftExactFunctor,
    RightExactFunctor,
    Kernel,
    Cokernel,
    Image,
    ExactSequence,
    Limit,
    Colimit,
    Product,
    Coproduct,
    Pullback,
    Pushout,
    Equalizer,
    Coequalizer,
    TerminalObject,
    InitialObject,
    ZeroObject,
    KanExtension,
    PreservesLimits,
    PreservesColimits,
)

from lean4py.differential_geometry import (
    Manifold,
    TangentSpace,
    TangentBundle,
    VectorField,
    Connection,
    RiemannianMetric,
    Geodesic,
    LeviCivitaConnection,
    CurvatureTensor,
    RiemannianManifold,
    Submanifold,
)

from lean4py.two_category import (
    TwoCategory,
    Cat,
    DoubleCategory,
    Bicategory,
    TwoMorphism,
    AdjunctionIn2Category,
    KanExtension2Category,
    LaxFunctor,
    Strict2Category,
    FunctorCategory,
)

from lean4py.automata_theory import (
    DFA,
    NFA,
    RegularExpression,
    PushdownAutomaton,
    TuringMachine,
    Grammar,
    ChomskyHierarchy,
    PumpingLemma,
    KleeneStar,
    MealyMachine,
    MooreMachine,
    FSM,
)

from lean4py.monoidal_categories import (
    MonoidalCategory,
    SymmetricMonoidalCategory,
    ClosedMonoidalCategory,
    BraidedMonoidalCategory,
    RigidCategory,
    TensorProduct,
    DualObject,
    EnrichedCategory,
    CoCartesianMonoidalCategory,
    CartesianMonoidalCategory,
    MonoidalFunctor,
    LaxMonoidalFunctor,
)

from lean4py.groebner_basis import (
    MonomialOrder,
    Polynomial,
    PolynomialRing,
    GroebnerBasis,
    BuchbergerAlgorithm,
    PolynomialIdeal,
    EliminationIdeal,
    IdealOperations,
)

from lean4py.symplectic_geometry import (
    SymplecticManifold,
    SymplecticForm,
    HamiltonianVectorField,
    PoissonBracket,
    MomentMap,
    Symplectomorphism,
    LagrangianSubmanifold,
    HamiltonianSystem,
    DarbouxCoordinates,
    ContactManifold,
    ReebVectorField,
)

from lean4py.markov_chains import (
    DiscreteTimeMarkovChain,
    ContinuousTimeMarkovChain,
    TransitionMatrix,
    StationaryDistribution,
    DetailedBalance,
    AbsorbingStates,
    MarkovChainMonteCarlo,
    HittingProbability,
    MixingTime,
)

from lean4py.noncommutative_geometry import (
    NoncommutativeSpace,
    SpectralTriple,
    DiracOperator,
    FredholmIndex,
    HochschildCohomology,
    CyclicCohomology,
    KHomology,
    FredholmModule,
    PseudodifferentialOperator,
    ConnesChernCharacter,
)

from lean4py.ergodic_theory import (
    ErgodicTransformation,
    MeasurePreservingMap,
    ErgodicTheorem,
    MixingTransformation,
    KolmogorovSinaiEntropy,
    BernoulliShift,
    PoincareRecurrence,
    InvariantMeasure,
    ErgodicDecomposition,
)

from lean4py.higher_category_theory import (
    InfinityCategory,
    KanComplex,
    NCategory,
    WeakEquivalence,
    HomotopyPushout,
    HomotopyPullback,
    SegalCategory,
    CompleteSegalSpace,
    Anima,
    InfinityTopos,
)

from lean4py.k_theory import (
    K0Group,
    K1Group,
    K2Group,
    KRing,
    TopologicalKTheory,
    AlgebraicKTheory,
    QuillenK,
    NilKTheory,
    HigherKGroup,
    AtiyahHirzebruch,
)

from lean4py.operator_algebras import (
    NormedSpace,
    HilbertSpace,
    BoundedOperator,
    CStarAlgebra,
    PositiveElement,
    VonNeumannAlgebra,
    SpectralTheorem,
    FunctionalCalculus,
    K0Group,
    K1Group,
    IndexTheory,
)

from lean4py.topology import (
    TopologicalSpace,
    MetricSpace,
    ContinuousFunction,
    Compactness,
    Connectedness,
    HausdorffSpace,
    OpenMap,
    ClosedMap,
)

from lean4py.measure_theory import (
    SigmaAlgebra,
    MeasurableSpace,
    Measure,
    LebesgueMeasure,
    MeasurableFunction,
    SimpleFunction,
    LebesgueIntegral,
    ProbabilityMeasure,
    BorelSigmaAlgebra,
)

from lean4py.functional_analysis import (
    NormedSpace,
    BanachSpace,
    InnerProductSpace,
    HilbertSpace,
    BoundedOperator,
    DualSpace,
    OperatorNorm,
)

from lean4py.combinatorics import (
    PigeonholePrinciple,
    CatalanNumber,
    BellNumber,
    DyckWord,
    SetFamily,
    SpernerTheorem,
    HallMarriage,
    BinomialCoefficient,
)

from lean4py.order_theory import (
    PartialOrder,
    TotalOrder,
    Lattice,
    CompleteLattice,
    HeytingAlgebra,
    BooleanAlgebra,
    GaloisConnection,
)

from lean4py.algebraic_structures import (
    Module,
    Algebra,
    TensorProduct,
    ExactSequence,
    FreeModule,
    SimpleModule,
)

from lean4py.integration import (
    BochnerIntegral,
    FubiniTheorem,
    ChangeOfVariables,
    Convolution,
    LpSpace,
    HolderInequality,
    MinkowskiInequality,
)

from lean4py.differential_equations import (
    ODEProblem,
    LipschitzCondition,
    PicardLindelof,
    FlowProperty,
    PhasePortrait,
    StabilityAnalysis,
)

from lean4py.calculus_of_variations import (
    Functional,
    EulerLagrangeEquation,
    HamiltonPrinciple,
    Brachistochrone,
    IsoperimetricProblem,
    NoetherTheorem,
)

from lean4py.control_theory import (
    LyapunovStability,
    StateSpaceRepresentation,
    Controllability,
    Observability,
    OptimalControl,
    KalmanFilter,
)

from lean4py.optimization_theory import (
    ConvexSet,
    ConvexFunction,
    LagrangeMultiplier,
    KKTConditions,
    Duality,
    SlaterCondition,
)

from lean4py.exceptions import (
    Lean4PyError,
    DimensionError,
    NotInvertibleError,
    ConvergenceError,
    GraphError,
    ProbabilityError,
)

__version__ = "1.25.0"
__all__ = [
    "Prop", "Prop_var", "implies", "and_", "or_", "not_", "iff",
    "Theorem", "ProofStep", "assume", "have", "exact", "apply", "rfl", "simp", "prove",
    "Set", "Set_from", "in_", "subset", "union", "intersection", "complement",
    "symmetric_difference", "is_disjoint", "is_overlapping",
    "difference", "cartesian", "power_set", "empty_set",
    "Magma", "Semigroup", "Monoid", "Group", "AbelianGroup", "Ring", "Field",
    "Nat", "nat", "zero", "succ", "pred", "is_zero",
    "nat_add", "nat_mul", "nat_sub", "nat_le", "nat_lt", "nat_eq",
    "Tactic", "tactic_rfl", "tactic_exact", "tactic_apply", "tactic_simp",
    "tactic_assume", "tactic_have", "TacticProof", "TacticState",
    "intros", "intros_tactic",
    "by_contra", "by_contra_tactic",
    "cases", "cases_tactic",
    "induction", "induction_tactic",
    "rewrite", "rewrite_tactic",
    "split", "split_tactic",
    "left", "left_tactic",
    "right", "right_tactic",
    "use", "use_tactic",
    "show", "show_tactic",
    "by", "by_tactic",
    "sorry", "sorry_tactic",
    "calc", "calc_tactic",
    "intro", "intro_tactic",
    "apply_tactic",
    "Prover", "truth_table_prove", "tableau_prove",
    "is_valid", "is_satisfiable", "find_counterexample",
    "Integer", "int_", "one",
    "gcd", "lcm", "bezout_identity",
    "is_prime", "prime_factors", "phi",
    "mod_exp", "mod_inverse", "divides", "coprime",
    "chinese_remainder", "fundamental_theorem_of_arithmetic",
    "IntegerInduction",
    "Vector", "zero_vector", "dot_product", "cross_product",
    "angle_between", "projection",
    "Matrix", "matrix", "identity_matrix", "zero_matrix",
    "matrix_mul", "matrix_vector_mul",
    "det", "matrix_minor", "matrix_inverse", "trace",
    "rank", "nullity", "eigenvalues", "eigenvectors",
    "is_linearly_independent", "span",
    "is_orthogonal", "is_orthonormal",
    "LinearMap", "linear_map", "characteristic_polynomial",
    "linear_regression_diagnostics",
    "solve_heat_equation", "solve_wave_equation",
    "solve_laplace_equation", "solve_poisson_equation",
    "moving_average", "autocovariance", "acf", "partial_acf",
    "linear_regression_ml", "logistic_regression",
    "Real", "real", "limit", "derivative", "integral",
    "series_sum", "converges", "is_continuous", "is_differentiable",
    "taylor_series", "lhopital_limit", "Sequence", "Function",
    "ProbabilitySpace", "Event", "RandomVariable",
    "ExpectedValue", "Variance", "StandardDeviation",
    "NormalDistribution", "BinomialDistribution", "PoissonDistribution",
    "UniformDistribution", "ExponentialDistribution",
    "bayes_theorem", "hypothesis_test", "confidence_interval",
    "Graph", "Vertex", "Edge",
    "bfs", "dfs", "shortest_path", "dijkstra",
    "bellman_ford", "is_connected", "is_bipartite",
    "connected_components", "has_cycle",
    "topological_sort", "eulerian_path",
    "spanning_tree", "minimum_spanning_tree",
    "is_complete", "graph_clique",
    "is_eulerian", "graph_coloring",
    "has_hamiltonian_path",
    "complement_graph",
    "mean", "median", "mode",
    "variance", "std_dev",
    "covariance", "correlation",
    "linear_regression",
    "skewness", "kurtosis",
    "ChainComplex", "CochainComplex", "LongExactSequence", "Ext", "Tor",
    "TopologicalSpace", "Presheaf", "Sheaf", "SheafCohomology", "AffineScheme", "Spec",
    "SheafOfRings", "SheafOfModules", "Scheme", "SchemeMorphism", "AffineMorphisms",
    "Site", "GrothendieckTopology", "Coverage", "ClosedSubscheme", "OpenSubscheme",
    "LieAlgebra", "LieSubalgebra", "LieAlgebraRepresentation", "AdjointRepresentation",
    "UniversalEnvelopingAlgebra", "SerreRelations", "RootSystem",
    "sl2_lie_algebra", "gl2_lie_algebra",
    "GroupRepresentation", "RepresentationHomomorphism", "Character", "IrreducibleRepresentation",
    "RegularRepresentation", "InducedRepresentation", "FrobeniusReciprocity",
    "MaschkeTheorem", "TensorProductRepresentations", "CharacterTable",
    "Groupoid", "PresheafOfGroupoids", "Stack", "DMStack", "ArtinStack", "ModuliSpace", "GITQuotient",
    "LieGroup", "ClosedSubgroup", "LieSubgroup", "UnitaryRepresentation", "AdjointRepresentation",
    "ExponentialMap", "BakerCampbellHausdorff", "LieGroupCorrespondence", "ClassicalGroups",
    "NormedSpace", "HilbertSpace", "BoundedOperator", "CStarAlgebra", "PositiveElement",
    "VonNeumannAlgebra", "SpectralTheorem", "FunctionalCalculus", "K0Group", "K1Group", "IndexTheory",
    "CompactLieGroup", "MaximalTorus", "WeightLattice", "CorootLattice", "WeylChamber",
    "WeylGroupOrbit", "HighestWeightRep", "WeylDimensionFormula", "CompactGroupClassification",
    "IntegrationOverGroup",
    "CechCohomology", "CechComplex", "SheafCohomologyGroups", "DerivedPushforward",
    "SpectralSequenceConvergence", "LeraySpectralSequence", "GrothendieckHigherDirectImage",
    "CartesianMorphism", "StackModuli", "PicardStack", "StabilityCondition",
    "GeometricInvariantTheory", "FormalSmoothMorphisms", "FormalUnramified",
    "FreeProbabilitySpace", "FreeRandomVariable", "FreeCentralLimitTheorem", "MarchenkoPastur",
    "FreeConvolution", "NoncommutativeSpace", "SpectralTriple", "ConnesDifferential",
    "SpectralFlow", "FredholmModule",
    "AdjointAction", "Centralizer", "CoadjointRepresentation", "KirillovOrbit",
    "FlagVariety", "BorelSubgroup", "AdjointOrbit", "NilpotentOrbit",
    "OrbitMethod", "RootDecomposition", "PositiveSystem", "BorelSubalgebra",
    "ParabolicSubalgebra", "VermaModuleIndex", "CharacterFormula",
    "DerivedCategory", "Hot", "TriangulatedCategory", "StableCategory",
    "DerivedFunctor", "RHom", "Lf", "Rf", "TorsionProduct", "ExtGroup",
    "HomologicalComplex", "ConnesExactTriangle",
    "FreeGroup", "FreeGroupCStarAlgebra", "ReducedFreeGroupCStar",
    "FreeGroupVonNeumannAlgebra", "II1Factor", "FreeProductCStarAlgebra",
    "AmalgamatedFreeProduct", "ReducedFreeProduct", "FourierTransformOnGroups",
    "PlancherelTheorem", "GroupCStarAlgebra", "CrossedProduct",
    "ComplexManifold", "AlmostComplexStructure", "HermitianMetric",
    "KahlerManifold", "KahlerMetric", "ChernConnection", "FirstChernClass",
    "HolomorphicSection", "ComplexProjectiveSpace", "HermitianEinsteinMetric",
    "CalabiYauManifold", "ComplexSubmanifold", "CohomologyRing", "HolomorphicVectorBundle",
    "SpectralSequence", "AdamsSpectralSequence", "SerreSpectralSequence", "ExactCouple",
    "Hypercohomology", "FilteredComplex", "CohomologySpectralSequence", "HomologySpectralSequence",
    "Topos", "SheafTopos", "BooleanTopos", "AbelianCategory", "Monomorphism", "Epimorphism",
    "ProjectiveObject", "InjectiveObject", "Generator", "Cogenerator", "ExactFunctor",
    "LeftExactFunctor", "RightExactFunctor", "Kernel", "Cokernel", "Image", "ExactSequence",
    "DynkinDiagram", "ClassificationTheorem", "Weight", "HighestWeightVector", "RootSystem",
    "WeylGroup", "VermaModule", "KostantForm", "SimpleLieAlgebra",
    "Coalgebra", "Bialgebra", "HopfAlgebra", "GroupAlgebra", "QuantumGroup",
    "ModuleAlgebra", "InvariantTheory", "RepresentationOfHopfAlgebra",
    "sl2_hopf", "sl2_quantized", "DualHopfAlgebra", "braided_category",
    "ModelCategory", "QuillenAdjunction", "HomotopyCategory", "HomotopyEquivalence",
    "CWComplex", "SimplicialModelCategory", "WhiteheadTheorem",
    "Cofibration", "Fibration", "WeakEquivalence", "WeakFactorizationSystem",
    "AnodyneExtension", "HomotopyCoherent",
    "ProjectiveSpace", "AlgebraicCurve", "RiemannRochResult", "Divisor", "LineBundle",
    "EllipticCurve", "Grassmannian", "RationalNormalCurve", "blowing_up",
    "SheafCohomologyAlgebraic",
    "NewtonRaphson", "SecantMethod", "BisectionMethod", "FixedPointIteration",
    "LagrangeInterpolation", "NewtonInterpolation", "GaussianQuadrature",
    "SimpsonRule", "RombergIntegration",
    "GraphIsomorphism", "Treewidth", "PlanarGraph", "EulerianCircuit",
    "HamiltonianCycle", "GraphColoring", "Matching", "VertexCover",
    "NetworkFlow", "GraphCentrality",
    "Limit", "Colimit", "Product", "Coproduct", "Pullback", "Pushout",
    "Equalizer", "Coequalizer", "TerminalObject", "InitialObject",
    "ZeroObject", "KanExtension", "PreservesLimits", "PreservesColimits",
    "Manifold", "TangentSpace", "TangentBundle", "VectorField", "Connection",
    "RiemannianMetric", "Geodesic", "LeviCivitaConnection", "CurvatureTensor",
    "RiemannianManifold", "Submanifold",
    "TwoCategory", "Cat", "DoubleCategory", "Bicategory", "TwoMorphism",
    "AdjunctionIn2Category", "KanExtension2Category", "LaxFunctor",
    "Strict2Category", "FunctorCategory",
    "DFA", "NFA", "RegularExpression", "PushdownAutomaton", "TuringMachine",
    "Grammar", "ChomskyHierarchy", "PumpingLemma", "KleeneStar",
    "MealyMachine", "MooreMachine", "FSM",
    "MonoidalCategory", "SymmetricMonoidalCategory", "ClosedMonoidalCategory",
    "BraidedMonoidalCategory", "RigidCategory", "TensorProduct", "DualObject",
    "EnrichedCategory", "CoCartesianMonoidalCategory", "CartesianMonoidalCategory",
    "MonoidalFunctor", "LaxMonoidalFunctor",
    "MonomialOrder", "Polynomial", "PolynomialRing", "GroebnerBasis",
    "BuchbergerAlgorithm", "PolynomialIdeal", "EliminationIdeal", "IdealOperations",
    "SymplecticManifold", "SymplecticForm", "HamiltonianVectorField", "PoissonBracket",
    "MomentMap", "Symplectomorphism", "LagrangianSubmanifold", "HamiltonianSystem",
    "DarbouxCoordinates", "ContactManifold", "ReebVectorField",
    "DiscreteTimeMarkovChain", "ContinuousTimeMarkovChain", "TransitionMatrix",
    "StationaryDistribution", "DetailedBalance", "AbsorbingStates",
    "MarkovChainMonteCarlo", "HittingProbability", "MixingTime",
    "NoncommutativeSpace", "SpectralTriple", "DiracOperator", "FredholmIndex",
    "HochschildCohomology", "CyclicCohomology", "KHomology", "FredholmModule",
    "PseudodifferentialOperator", "ConnesChernCharacter",
    "ErgodicTransformation", "MeasurePreservingMap", "ErgodicTheorem",
    "MixingTransformation", "KolmogorovSinaiEntropy", "BernoulliShift",
    "PoincareRecurrence", "InvariantMeasure", "ErgodicDecomposition",
    "InfinityCategory", "KanComplex", "NCategory",
    "HomotopyPushout", "HomotopyPullback", "SegalCategory", "CompleteSegalSpace",
    "Anima", "InfinityTopos",
     "K0Group", "K1Group", "K2Group", "KRing", "TopologicalKTheory",
     "AlgebraicKTheory", "QuillenK", "NilKTheory", "HigherKGroup", "AtiyahHirzebruch",
     "TopologicalSpace", "MetricSpace", "ContinuousFunction", "Compactness",
     "Connectedness", "HausdorffSpace", "OpenMap", "ClosedMap",
     "SigmaAlgebra", "MeasurableSpace", "Measure", "LebesgueMeasure",
     "MeasurableFunction", "SimpleFunction", "LebesgueIntegral", "ProbabilityMeasure",
     "BorelSigmaAlgebra",
     "NormedSpace", "BanachSpace", "InnerProductSpace", "HilbertSpace",
     "BoundedOperator", "DualSpace", "OperatorNorm",
     "PigeonholePrinciple", "CatalanNumber", "BellNumber", "DyckWord",
     "SetFamily", "SpernerTheorem", "HallMarriage", "BinomialCoefficient",
     "PartialOrder", "TotalOrder", "Lattice", "CompleteLattice",
     "HeytingAlgebra", "BooleanAlgebra", "GaloisConnection",
     "Module", "Algebra", "TensorProduct", "ExactSequence",
     "FreeModule", "SimpleModule",
     "BochnerIntegral", "FubiniTheorem", "ChangeOfVariables",
     "Convolution", "LpSpace", "HolderInequality", "MinkowskiInequality",
     "ODEProblem", "LipschitzCondition", "PicardLindelof",
     "FlowProperty", "PhasePortrait", "StabilityAnalysis",
     "Functional", "EulerLagrangeEquation", "HamiltonPrinciple",
     "Brachistochrone", "IsoperimetricProblem", "NoetherTheorem",
     "LyapunovStability", "StateSpaceRepresentation",
     "Controllability", "Observability", "OptimalControl", "KalmanFilter",
     "ConvexSet", "ConvexFunction", "LagrangeMultiplier",
     "KKTConditions", "Duality", "SlaterCondition",
 ]